# Generated by Django 5.2.8 on 2025-12-30 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_card_deadline_card_description_card_required_skills'),
        ('notifications', '0002_alter_notification_task'),
        ('tasks', '0002_alter_task_deadline_alter_task_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='checklist_id',
        ),
        migrations.RemoveField(
            model_name='list',
            name='board_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='list_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tasks',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author_id',
            new_name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='boards.card'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='cards',
            field=models.ManyToManyField(related_name='tags', to='boards.card'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Checklist',
        ),
        migrations.DeleteModel(
            name='ChecklistItem',
        ),
        migrations.DeleteModel(
            name='List',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
