# Generated by Django 5.2.8 on 2025-12-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_card_members_checklist_checklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='required_skills',
            field=models.TextField(blank=True, default='', help_text='Kỹ năng yêu cầu'),
        ),
    ]
