# Generated by Django 5.2.8 on 2025-12-23 08:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_remove_board_owner_id_board_owner_board_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
