# Generated by Django 5.2.8 on 2025-12-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_card_deadline_card_description_card_required_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
